### ISSUE TITLE
nil pointer dereference caused by tests on main branch

### ISSUE THREAD

**Issue by jxsl13** [pb33f/libopenapi#164]
```
=== RUN   TestResolver_CheckForCircularReferences_DigitalOcean
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1029b9fcc]

goroutine 9527 [running]:
github.com/vmware-labs/yaml-jsonpath/pkg/yamlpath.newPath.func1(0x14003167560?, 0x102e223b0?)
        /Users/john/go/pkg/mod/github.com/vmware-labs/yaml-jsonpath@v0.3.2/pkg/yamlpath/path.go:54 +0x1c
github.com/vmware-labs/yaml-jsonpath/pkg/yamlpath.(*Path).find(0x102dc0dc0?, 0x1?, 0x102af94cf?)
        /Users/john/go/pkg/mod/github.com/vmware-labs/yaml-jsonpath@v0.3.2/pkg/yamlpath/path.go:29 +0x2c
github.com/vmware-labs/yaml-jsonpath/pkg/yamlpath.(*Path).Find(...)
        /Users/john/go/pkg/mod/github.com/vmware-labs/yaml-jsonpath@v0.3.2/pkg/yamlpath/path.go:25
github.com/pb33f/libopenapi/index.(*SpecIndex).lookupRemoteReference(0x14002ab8a00, {0x14000364fc0?, 0x2c?})
        /Users/john/Desktop/Development/libopenapi/index/find_component.go:206 +0x30c
github.com/pb33f/libopenapi/index.(*SpecIndex).lookupFileReference(0x14002ab8a00, {0x140034320f0, 0x2c})
        /Users/john/Desktop/Development/libopenapi/index/find_component.go:258 +0x274
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent.func2({0x140034320f0?, 0x10286bdb4?})
        /Users/john/Desktop/Development/libopenapi/index/find_component.go:40 +0x3c
github.com/pb33f/libopenapi/index.(*SpecIndex).performExternalLookup(0x14002ab8a00, {0x14002bedc80, 0x2, 0x2}, {0x140034320f0, 0x2c}, 0x14002732e88, 0x14002ac9e00)
        /Users/john/Desktop/Development/libopenapi/index/find_component.go:356 +0x158
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent(0x14002ab8a00, {0x140000b4990, 0x2b}, 0x0?)
        /Users/john/Desktop/Development/libopenapi/index/find_component.go:83 +0x198
github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs.func1(0x14003a72a20, 0x8, {0x14001dd98f0, 0xd, 0x0?})
        /Users/john/Desktop/Development/libopenapi/index/extract_refs.go:411 +0x64
created by github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs
        /Users/john/Desktop/Development/libopenapi/index/extract_refs.go:459 +0x3bc
FAIL    github.com/pb33f/libopenapi/resolver    61.442s
```

I also have a lot of flaky test cases that fail unexpectedly, mostly due to GitHub struggling.

How about spinning up our own small http server for fetching remote docs?
Or improve the default http.Get function and add some retry mechanisms based on http response codes and http headers like https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

**Comment by jxsl13** [comment]
flaky test :/
