### ISSUE TITLE
Panic while trying to Unmarshal a Schema

### ISSUE THREAD

**Issue by PatOConnor43** [pb33f/libopenapi#273]
Hey 👋 thanks for the library!

I'm trying to use it to build an OpenAPI 3.1 spec from a different input. I have a constant string that I want to use for the Schema so I'm attempting to `Unmarshal` that as a `"github.com/pb33f/libopenapi/datamodel/high/base".Schema`. Here's a Go file that should be able to reproduce the issue if you `go run` it:

```golang
package main

import (
	"encoding/json"
	"fmt"

	"github.com/pb33f/libopenapi"
	v3highbase "github.com/pb33f/libopenapi/datamodel/high/base"
	v3high "github.com/pb33f/libopenapi/datamodel/high/v3"
	openapi_orderedmap "github.com/pb33f/libopenapi/orderedmap"
)

func main() {

	b := []byte(`{"openapi": "3.1.0", "info": {"title": "My API", "version": "1.0.0"}, "paths": {}}`)

	document, err := libopenapi.NewDocument(b)
	if err != nil {
		fmt.Println("Error creating document")
		panic(err)
	}
	mod, errs := document.BuildV3Model()
	if errs != nil && len(errs) > 0 {
		fmt.Println("Error building model")
		panic(err)
	}

	newSchema := []byte(`{"type": ["object"], "properties": {"first": {"type": ["string"]}}}`)

	var schema v3highbase.Schema
	err = json.Unmarshal(newSchema, &schema) // This is where I get the panic
	if err != nil {
		panic(err)
	}


	mediaType := v3high.MediaType{
		Schema: v3highbase.CreateSchemaProxy(&schema),
	}

	responseContent := openapi_orderedmap.New[string, *v3high.MediaType]()
	responseContent.Set("application/json", &mediaType)

	codes := openapi_orderedmap.New[string, *v3high.Response]()
	codes.Set("200", &v3high.Response{
		Description: "A collection of things",
		Content:     responseContent,
	})

	responses := v3high.Responses{
		Codes: codes,
	}

	newPath := v3high.PathItem{
		Description: "Interact with a collection of things",
		Get: &v3high.Operation{
			Description: "Get a collection of things",
			OperationId: "getThings",
			Responses:   &responses,
		},
	}

	mod.Model.Paths.PathItems.Set("/things", &newPath)
	b, document, mod, errs = document.RenderAndReload()
	if errs != nil && len(errs) > 0 {
		fmt.Println("Error rendering model")
		panic(err)
	}
	fmt.Println(string(b))
}
```

The stacktrace looks like this:
```
go run schema_issue.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100e4a5ac]

goroutine 1 [running]:
github.com/wk8/go-ordered-map/v2.(*OrderedMap[...]).UnmarshalJSON(0x41?, {0x1400016e1b3?, 0x2?, 0x14000148388?})
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/wk8/go-ordered-map/v2@v2.1.8/json.go:105 +0x1c
encoding/json.(*decodeState).object(0x14000148360, {0x1010fbd40?, 0x1400017c638?, 0x10100ad00?})
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/encoding/json/decode.go:604 +0x5c4
encoding/json.(*decodeState).value(0x14000148360, {0x1010fbd40?, 0x1400017c638?, 0xa?})
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/encoding/json/decode.go:374 +0x40
encoding/json.(*decodeState).object(0x14000148360, {0x10106e300?, 0x1400017c508?, 0x100c73160?})
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/encoding/json/decode.go:755 +0xa94
encoding/json.(*decodeState).value(0x14000148360, {0x10106e300?, 0x1400017c508?, 0x100c72c40?})
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/encoding/json/decode.go:374 +0x40
encoding/json.(*decodeState).unmarshal(0x14000148360, {0x10106e300?, 0x1400017c508?})
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/encoding/json/decode.go:181 +0x104
encoding/json.Unmarshal({0x1400016e190, 0x43, 0x43}, {0x10106e300, 0x1400017c508})
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/encoding/json/decode.go:108 +0xe4
main.main()
        /Users/patrickoconnor/workspace/endpoints-specs/schema_issue/schema_issue.go:31 +0x130
exit status 2
```

**Through debugging this issue I also found out that removing the `properties` field from the Schema seemed to result in a successful Unmarshal**

Because of that I tried to add an initialized ordered map before Unmarshalling:
```golang
        newSchema := []byte(`{"type": ["object"], "properties": {"first": {"type": ["string"]}}}`)

	var schema v3highbase.Schema
	schema.Properties = openapi_orderedmap.New[string, *v3highbase.SchemaProxy]()
	err = json.Unmarshal(newSchema, &schema)
	if err != nil {
		panic(err)
	}
```

That resulted in a different panic:
```
go run schema_issue.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103046b0c]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
        /Users/patrickoconnor/.asdf/installs/golang/1.22.0/go/src/sync/mutex.go:83
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).Schema(0x0?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/base/schema_proxy.go:79 +0x1c
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).BuildSchema(0x14000158540)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/base/schema_proxy.go:151 +0x40
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).MarshalYAML(0x103618d80?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/base/schema_proxy.go:186 +0x22c
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x14000162a50, 0x140001d1040, 0x14000128960)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:453 +0x1a9c
github.com/pb33f/libopenapi/orderedmap.(*Map[...]).ToYamlNode(0x103301500, {0x1032f09e0, 0x14000162a50}, {0x0, 0x0})
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/orderedmap/builder.go:78 +0xec
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x14000162a50, 0x140001d0dc0, 0x14000128900)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:431 +0x1fb0
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).Render(0x14000162a50)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:257 +0x234
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).MarshalYAML(0x103618d80?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/base/schema_proxy.go:191 +0x26c
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x14000162a00, 0x140001d0c80, 0x14000128840)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:453 +0x1a9c
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).Render(0x14000162a00)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:257 +0x234
github.com/pb33f/libopenapi/datamodel/high/v3.(*MediaType).MarshalYAML(0x103618da0?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/media_type.go:66 +0x38
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x140001629b0, 0x140001d0b40, 0x140001287e0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:453 +0x1a9c
github.com/pb33f/libopenapi/orderedmap.(*Map[...]).ToYamlNode(0x103300300, {0x1032f09e0, 0x140001629b0}, {0x0, 0x0})
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/orderedmap/builder.go:78 +0xec
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x140001629b0, 0x140001d08c0, 0x14000128780)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:431 +0x1fb0
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).Render(0x140001629b0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:257 +0x234
github.com/pb33f/libopenapi/datamodel/high/v3.(*Response).MarshalYAML(0x1031ddfe0?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/response.go:72 +0x38
github.com/pb33f/libopenapi/datamodel/high/v3.(*Responses).MarshalYAML(0x140001487e0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/responses.go:140 +0x2f4
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x14000162910, 0x140001d03c0, 0x140001286c0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:453 +0x1a9c
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).Render(0x14000162910)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:257 +0x234
github.com/pb33f/libopenapi/datamodel/high/v3.(*Operation).MarshalYAML(0x103618da0?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/operation.go:119 +0x38
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x140001628c0, 0x140001d0140, 0x140001285a0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:453 +0x1a9c
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).Render(0x140001628c0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:257 +0x234
github.com/pb33f/libopenapi/datamodel/high/v3.(*PathItem).MarshalYAML(0x1031ddf60?)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/path_item.go:211 +0x38
github.com/pb33f/libopenapi/datamodel/high/v3.(*Paths).MarshalYAML(0x1400011e210)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/paths.go:131 +0x330
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).AddYAMLNode(0x140001626e0, 0x1400011b900, 0x14000128420)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:453 +0x1a9c
github.com/pb33f/libopenapi/datamodel/high.(*NodeBuilder).Render(0x140001626e0)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/node_builder.go:257 +0x234
github.com/pb33f/libopenapi/datamodel/high/v3.(*Document).RenderJSON(0xd0?, {0x1030eb25c, 0x2})
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/datamodel/high/v3/document.go:177 +0x44
github.com/pb33f/libopenapi.(*document).Render(0x14000158400)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/document.go:236 +0x170
github.com/pb33f/libopenapi.(*document).RenderAndReload(0x14000158400)
        /Users/patrickoconnor/workspace/goworkspace/pkg/mod/github.com/pb33f/libopenapi@v0.15.15/document.go:202 +0x24
main.main()
        /Users/patrickoconnor/workspace/endpoints-specs/schema_issue/schema_issue.go:64 +0x4d8
exit status 2
```

I'm feeling like this might _not_ be the expected way to take some bytes and turn it into a Schema object so I'm open to other ideas. I'm planning on the users of the tool I'm writing to be able to just write a schema and I can take that string and put it in the right place in the OpenAPI spec.

Thanks again for all the work on this library and any help you can provide!

**Comment by PatOConnor43** [comment]
After thinking about it more, I actually just ended up building these schemas into the initial schema. This is how I did that:
```go
userSchemas := map[string]map[string]interface{}{}
for _, resource := range input.Resources {
	var m map[string]interface{}
	_ = json.Unmarshal(resource.SchemaRaw, &m)
	userSchemas[resource.Name] = m
}
renderedSchemas, _ := json.Marshal(userSchemas)

initialSchema := fmt.Sprintf(`{
	"openapi": "3.1.0",
	"info": {
		"title": "My API",
		"version": "1.0.0"
	},
	"components": {
		"schemas": %s,
		"parameters": {}
	},
	"paths": {}
}`, renderedSchemas)

b := []byte(initialSchema)
```

It'd still be nice to know if there's a way to create a schema from bytes but this unblocks me for now 🚀

**Comment by daveshanley** [comment]
Hi, I ran the code and the issue is because you need to use the `func NewSchemaProxy(schema *low.NodeReference[*base.SchemaProxy]) *SchemaProxy` function to create a high level schema. 

The high level model needs a low level model, which is [explained here](https://pb33f.io/libopenapi/model/)

So just using an empty struct is going to fail, the panic happens because there is no mutex available in the schema (which is required lower down the stack). 

If you'd like to add a new feature request to add a new schema from bytes, it could be put into the backlog.

**Comment by PatOConnor43** [comment]
Ah okay thanks. The combination of the docs link and looking at the unit tests for schema_test.go helped me out. Here's a function that distills what I was trying to do:
```go
func printSchema() {
	yamlStr := `type:
- object
properties:
  id:
    type:
    - string
  name:
    type:
    - string
  parent:
    type:
    - string`

	var node yaml.Node
	yaml.Unmarshal([]byte(yamlStr), &node)

	lowProxy := new(v3lowbase.SchemaProxy)
	lowProxy.Build(context.Background(), nil, node.Content[0], nil)

	sp := v3highbase.NewSchemaProxy(&low.NodeReference[*v3lowbase.SchemaProxy]{
		Value:     lowProxy,
		ValueNode: &node,
	})

	a, _ := sp.Schema().Render()
	fmt.Fprintf(os.Stderr, "Schema: \n%s\n", string(a))

}
```

Calling this function prints:
```
Schema:
type: object
properties:
    id:
        type: string
    name:
        type: string
    parent:
        type: string

```

Which shows me that it actually parsed correctly. Thanks for the help!

I'm not sure if an issue is required to add a "new schema from bytes" api. I can work with this now that I'm more familiar with what is expected.
