### ISSUE TITLE
Bug: `panic: runtime error: invalid memory address or nil pointer dereference` Building Model

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#48]
This doc: https://raw.githubusercontent.com/speakeasy-api/openapi-directory/main/APIs/opensuse.org/obs/2.10.50/openapi.yaml

Produces the below error:

```
go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6938d4]

goroutine 1 [running]:
github.com/vmware-labs/yaml-jsonpath/pkg/yamlpath.(*Path).find(0xc00088b140?, 0x5b?, 0x78a586?)
        /home/trist/go/pkg/mod/github.com/vmware-labs/yaml-jsonpath@v0.3.2/pkg/yamlpath/path.go:29 +0x14
github.com/vmware-labs/yaml-jsonpath/pkg/yamlpath.(*Path).Find(...)
        /home/trist/go/pkg/mod/github.com/vmware-labs/yaml-jsonpath@v0.3.2/pkg/yamlpath/path.go:25
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponentInRoot(0xc000101800, {0xc000182180, 0x5a})
        /home/trist/go/pkg/mod/github.com/pb33f/libopenapi@v0.4.3/index/spec_index.go:1836 +0x99
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent(0xc000101800, {0xc000182180, 0x5a}, 0x29?)
        /home/trist/go/pkg/mod/github.com/pb33f/libopenapi@v0.4.3/index/spec_index.go:1572 +0x2f2
github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs(0xc000101800, {0xc000769680, 0x24, 0xc0005a60a0?})
        /home/trist/go/pkg/mod/github.com/pb33f/libopenapi@v0.4.3/index/spec_index.go:1532 +0x2b0
github.com/pb33f/libopenapi/index.NewSpecIndex(0xc0000d37c0)
        /home/trist/go/pkg/mod/github.com/pb33f/libopenapi@v0.4.3/index/spec_index.go:245 +0x786
github.com/pb33f/libopenapi/datamodel/low/v3.CreateDocument(0xc0000d3860)
        /home/trist/go/pkg/mod/github.com/pb33f/libopenapi@v0.4.3/datamodel/low/v3/create_document.go:25 +0x17d
github.com/pb33f/libopenapi.(*document).BuildV3Model(0xc00062a000?)
        /home/trist/go/pkg/mod/github.com/pb33f/libopenapi@v0.4.3/document.go:150 +0x4e
main.main()
        /home/trist/workspace/scratch/main.go:33 +0x32
```

with this code:

```go
package main

import (
	"io"
	"net/http"

	"github.com/pb33f/libopenapi"
)

func read() []byte {
	res, err := http.Get("https://raw.githubusercontent.com/speakeasy-api/openapi-directory/main/APIs/opensuse.org/obs/2.10.50/openapi.yaml")
	if err != nil {
		panic(err)
	}
	defer res.Body.Close()

	data, err := io.ReadAll(res.Body)
	if err != nil {
		panic(err)
	}

	return data
}

func main() {
	data := read()

	doc, err := libopenapi.NewDocument(data)
	if err != nil {
		panic(err)
	}

	_, errs := doc.BuildV3Model()
	if len(errs) > 0 {
		panic(errs)
	}
}
```

**Comment by daveshanley** [comment]
Will investigate, thanks for finding!

**Comment by daveshanley** [comment]
looks like more crazy $ref issues. This is one horrible auto-generated spec.

For example:

`$ref: "#/paths/~1architectures/get/responses/200/content/application~1xml;%20charset=utf-8/schema`

**Comment by daveshanley** [comment]
Quick question, **Has this spec ever worked? Have those references ever been picked up?**

The more I look at this, the less sure I am there is a way to resolve it, that path is invalid and it cannot be found using JSONPath. The reason this is panicing (which I can fix) is that the JSON Path being generated from that component reference is currently invalid. This is the type of thing which is causing the panic

`$.paths./architectures.get.responses.401.content.application/xml;%20charset=utf-8.['schema']`

Should actually be:

`$.paths./architectures.get.responses.401.content['application/xml;%20charset=utf-8']['schema']`

However this path cannot be found. I've tried it against a few different tools to double check it's not the library that `libopenapi` is using under the hood. (https://github.com/vmware-labs/yaml-jsonpath). It's not.

When I load up the spec in my IDE, those references cannot be followed, they can't be looked up there either.

```yaml
          content:
            application/xml; charset=utf-8:
              example:
                code: unknown_architecture
                summary: "Architecture does not exist: x999"
              schema:
                $ref: "#/paths/~1architectures/get/responses/401/content/application~1xml;%20charset=utf-8/schema"
          description: Not Found.
```

This is clearly auto-generated, but it's doing something I don't think I can fix, the path simply isn't reachable, so whilst this spec has valid syntax, it's not actually valid because those paths cannot be looked-up using code (at least, not the way I have been testing)

**Comment by TristanSpeakEasy** [comment]
Yeah I just had a quick check with an older version of our tooling and it validates that it is not valid (can't resolve the ref as you say), the issues is definitely just that a panic is thrown in this case where it would be better to receive a usable error

**Comment by daveshanley** [comment]
I'm going to try a couple of other things to see if I can shoehorn in a lookup, but it's not looking great, I can't trick the library into finding those whacky paths, either way, I will implement some cleaner handling and prevent the panic.

**Comment by daveshanley** [comment]
Oh wow, I made it work, just needed a couple more tweaks to get the path right. New patch inbound!

**Comment by daveshanley** [comment]
This should be resolved in `v0.4.4`. Please confirm when convenient.
