### ISSUE TITLE
Concurrency Bug: Unable to parse Digial Ocean spec

### ISSUE THREAD

**Issue by bitomaxsp** [pb33f/libopenapi#91]
Steps to reproduce:

1. git clone https://github.com/digitalocean/openapi
2. cd openapi/specification
3. Create simple main.go with the following content:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/pb33f/libopenapi"
	v3high "github.com/pb33f/libopenapi/datamodel/high/v3"
)

func main() {
	doc, err := readV3ModelFromFile(os.Args[1])
	if err != nil {
		println(err.Error())
		os.Exit(1)
	}
	_ = doc
}

func readV3ModelFromFile(filename string) (*libopenapi.DocumentModel[v3high.Document], error) {
	// load an OpenAPI 3 specification from bytes
	data, _ := os.ReadFile(filename)

	// create a new document from specification bytes
	document, err := libopenapi.NewDocument(data)
	// if anything went wrong, an error is thrown
	if err != nil {
		return nil, fmt.Errorf("schema: cannot create new document: %w", err)
	}
	// because we know this is a v3 spec, we can build a ready to go model from it.
	model, errors := document.BuildV3Model()

	// if anything went wrong when building the v3 model, a slice of errors will be returned
	if len(errors) > 0 {
		for i := range errors {
			log.Printf("schema: %s", errors[i])
		}
		return nil, fmt.Errorf("schema: unable to build open api model")
	}

	return model, nil
}
```
4. go run main.go DigitalOcean-public.v2.yaml

Result:
```shell
fatal error: concurrent map writes

goroutine 288 [running]:
github.com/pb33f/libopenapi/index.(*SpecIndex).lookupFileReference(0x14000310000, {0x140002ad800, 0x26})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.0/index/find_component.go:220 +0x1d4
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent.func2({0x140002ad800?, 0x10126de40?})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.0/index/find_component.go:37 +0x3c
github.com/pb33f/libopenapi/index.(*SpecIndex).performExternalLookup(0x14000310000, {0x14000010320, 0x2, 0x1?}, {0x140002ad800, 0x26}, 0x14000562e98, 0x140002519a0)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.0/index/find_component.go:286 +0x80
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent(0x14000310000, {0x14000238a20, 0x25}, 0x0?)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.0/index/find_component.go:80 +0x194
github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs.func1(0x140003521e0, 0xfc, {0x1400038ea80, 0x123, 0x0?})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.0/index/extract_refs.go:331 +0x64
created by github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.0/index/extract_refs.go:377 +0x370
DigitalOcean-public.v2.yaml
```

Expected behavior: Should able to parse multi file digital ocean spec

**Comment by daveshanley** [comment]
Strangely, a similar test in the suite does something close without a race condition. This should not happen. There should be no concurrent map writes that aren't using a mutex. I'll investigate.

**Comment by daveshanley** [comment]
You can see a test for this exact case here: 

https://github.com/pb33f/libopenapi/blob/main/index/spec_index_test.go#L104

**Comment by bitomaxsp** [comment]
I have tested it. Rarely reproduceable. But if you try to run example code many times it hits again.

```bash
fatal error: concurrent map read and map write

goroutine 17540 [running]:
github.com/pb33f/libopenapi/index.(*SpecIndex).performExternalLookup(0x14006575200, {0x14007f26100, 0x2, 0x1?}, {0x14007b31170, 0x2c}, 0x140027f0e98, 0x1400657f860)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/find_component.go:290 +0x64
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent(0x14006575200, {0x140060f1e90, 0x2b}, 0x0?)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/find_component.go:82 +0x194
github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs.func1(0x14006527e60, 0x8, {0x140060cd6d0, 0xa, 0x0?})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/extract_refs.go:367 +0x64
created by github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/extract_refs.go:413 +0x370

goroutine 1 [chan receive]:
github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs(0x14000080d80, {0x1400033a000, 0x123, 0x140001218b8?})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/extract_refs.go:420 +0x440
github.com/pb33f/libopenapi/index.createNewIndex(0x30?, 0x14000080d80)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/spec_index.go:76 +0x174
github.com/pb33f/libopenapi/index.NewSpecIndexWithConfig(0x14000104d20, 0x14000239710)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/spec_index.go:39 +0xf0
github.com/pb33f/libopenapi/datamodel/low/v3.createDocument(0x14000104dc0, 0x14000252b70)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/datamodel/low/v3/create_document.go:45 +0x188
github.com/pb33f/libopenapi/datamodel/low/v3.CreateDocumentFromConfig(...)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/datamodel/low/v3/create_document.go:29
github.com/pb33f/libopenapi.(*document).BuildV3Model(0x14000010060)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/document.go:197 +0xac
main.readV3ModelFromFile({0x16f25b747?, 0x100bd7f14?})
	/Users/dmitry/projects/digital-ocean-api/main.go:57 +0x34
main.main()
	/Users/dmitry/projects/digital-ocean-api/main.go:14 +0x3c

goroutine 10947 [semacquire]:
gopkg.in/yaml%2ev3.yaml_parser_parse_block_mapping_key(0x140040bf800, 0x140040bfab0, 0x0?)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:822 +0x7c
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0x100f5fcc0?, 0x140040bfab0?)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:188 +0x114
gopkg.in/yaml%2ev3.yaml_parser_parse(0x140040bf800?, 0x140040bfab0?)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:129 +0x90
gopkg.in/yaml%2ev3.(*parser).peek(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:106 +0x30
gopkg.in/yaml%2ev3.(*parser).mapping(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:279 +0x114
gopkg.in/yaml%2ev3.(*parser).parse(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x120
gopkg.in/yaml%2ev3.(*parser).parseChild(0x140040bf800?, 0x1400441a960)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197 +0x20
gopkg.in/yaml%2ev3.(*parser).mapping(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x1b8
gopkg.in/yaml%2ev3.(*parser).parse(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x120
gopkg.in/yaml%2ev3.(*parser).parseChild(0x140040bf800?, 0x1400441a820)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197 +0x20
gopkg.in/yaml%2ev3.(*parser).mapping(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x1b8
gopkg.in/yaml%2ev3.(*parser).parse(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x120
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).document(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:206 +0x80
gopkg.in/yaml%2ev3.(*parser).parse(0x140040bf800)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:159 +0xb4
gopkg.in/yaml%2ev3.unmarshal({0x14004420000, 0x4e8, 0x4e9}, {0x100f37820?, 0x1400441a6e0}, 0x0?)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:161 +0x2b8
gopkg.in/yaml%2ev3.Unmarshal(...)
	/Users/dmitry/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89
github.com/pb33f/libopenapi/index.(*SpecIndex).lookupFileReference(0x14003c38000, {0x1400355bef0, 0x25})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/find_component.go:219 +0x214
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent.func2({0x1400355bef0?, 0x14000502680?})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/find_component.go:39 +0x3c
github.com/pb33f/libopenapi/index.(*SpecIndex).performExternalLookup(0x14003c38000, {0x14003acde00, 0x2, 0x1?}, {0x1400355bef0, 0x25}, 0x14000f13e98, 0x14003c32b40)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/find_component.go:293 +0x84
github.com/pb33f/libopenapi/index.(*SpecIndex).FindComponent(0x14003c38000, {0x1400355bef0, 0x25}, 0x0?)
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/find_component.go:69 +0x1c4
github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs.func1(0x1400376d140, 0x1, {0x1400383d090, 0xa, 0x6669747265632f73?})
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/extract_refs.go:367 +0x64
created by github.com/pb33f/libopenapi/index.(*SpecIndex).ExtractComponentsFromRefs
	/Users/dmitry/go/pkg/mod/github.com/pb33f/libopenapi@v0.6.2/index/extract_refs.go:413 +0x370
```

**Comment by bitomaxsp** [comment]
I'd assume that every `map` in `SpecIndex` that changes concurrently must be under lock

**Comment by daveshanley** [comment]
Damn. OK. I guess we need to harden it even more. More locks coming!

**Comment by daveshanley** [comment]
Would you be able to try `v0.6.3`? All tests pass with `-race` flag, no race conditions are detected after locating the rogue maps.

**Comment by bitomaxsp** [comment]
I have been running parsing using script for ~20 minutes. It never crashed. So i think we can close this issue.
Thanks a lot for support!
